# Build Stage
FROM node:18-alpine3.21 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN ls -la
RUN npm run build

# Development Stage
FROM node:18-alpine3.21 AS development-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --only=development
COPY --from=build-stage /app/dist ./dist
RUN ls -la
EXPOSE 5000
CMD ["npm", "run", "start:dev"]